config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/signout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/users/:user_id/recipes' => 'users#show'
  post '/users/:user_id/recipes/new' => 'recipes#create'

  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'

  post '/recipes/:recipe_id' => 'comments#create'

  resources :users do
    resources :recipes, except: [:destroy]
  end
  resources :recipes do
    resources :comments
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :recipe
  belongs_to :user

  validates_inclusion_of :rating, :in => 1..5, message: "is between 1-5"

  def user_name
    user.name
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  
  def new
    @comment = Comment.new
  end

  def show
    comment = Comment.find_by(user: current_user, recipe: find_by_recipe_id)
  end

  def create
    if logged_in?
      comment = Comment.new(comment_params)
      comment.recipe = find_by_recipe_id
      comment.user = current_user
        if comment.description.empty? || comment.rating == nil
          redirect_to recipe_path(comment.recipe), alert: "Please fill out all fields"
        else
          comment.save
          render json: comment.to_json(only: [:rating, :description, :id, :recipe_id],
                                    include: [user: { only: [:name]}])
        end
      end
    end

  def edit
    @comment = find_by_id(Comment)
  end

  def update
    comment = find_by_id(Comment)
    respond_to do |format|
      if comment.update(comment_params)
        format.html { redirect_to recipe_path(comment.recipe), notice: 'Comment was successfully updated.' }
        format.json { render json: comment.to_json(only: [:rating, :description, :id, :recipe_id],
                                          include: [user: { only: [:name]}])}
      else
        format.html { redirect_to recipe_path(comment.recipe), alert: "That was not a valid comment or rating... Please try again!" }
        format.json { render json: comment.errors, status:400 }
      end
    end
  end

  def destroy
    id = params["id"].to_i
    comment = Comment.find_by(id: id)
    if current_user == comment.user
      comment.delete
      flash[:notice] = "Comment has been deleted"
    else
      redirect_to recipe_path(comment.recipe), alert: "You can only delete your own comments"
    end
  end

  private

  def comment_params
     params.fetch(:comment, {}).permit(:rating, :description, :user)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit_form.html.erb
<div class="edit_comment_form">
<%= form_for [recipe, comment] do |f| %>
  <%= render 'layouts/form_errors', form: comment %>
  <div>Rating: (1-5)</div> <div><%= f.text_field :rating %></div>
  <div>Description</div> <div><%= f.text_area :description, size: "50x5" %></div>
  <%= f.button :Submit, id: 'submit_edit_comment' %>
<% end %>
</div>

app/views/comments/_form.html.erb
<div class="comment_form">
<%= form_for [recipe, comment] do |f| %>
  <%= render 'layouts/form_errors', form: comment %>
  <div>Rating: (1-5)</div> <div><%= f.text_field :rating %></div>
  <div>Description</div> <div><%= f.text_area :description, size: "50x5" %></div>
  <%= f.button :Submit, id: 'submit_comment' %>
<% end %>
</div>

app/views/comments/_list_comments.html.erb
<div class="comments_container">
<% if comments.count == 0 %>
  <h2 class="no_comment_message">There are no comments posted yet, be the first to create one!</h2>
  <% else %>
<%end%>
  <% comments.each do |comment| %>
    <div class='new_comment_<%=comment.id%>'>
      <h3 class="cheading">
        <%= comment.user.name %><%= " gives #{comment.rating} out of 5 stars!"%>
      </h3>
      <p class="cdescription">
        <%= comment.description %>
      </p>

      <%= link_to "Edit", edit_recipe_comment_path(comment.recipe, comment),class: 'ecomment' if current_user == comment.user%>

      <%= link_to "Delete", comment_path(comment), method: :delete, class: 'dcomment' if current_user == comment.user%>

  </div>
  <% end %>
</div>

app/views/comments/edit.html.erb
<h3> Edit your Comment: </h3>
<%= render 'comments/edit_form', comment: @comment, recipe: @comment.recipe %>

app/views/comments/new.html.erb
<%= render 'comments/form', comment: @comment, recipe: @recipe %>