config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/signout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/users/:user_id/recipes' => 'users#show'
  post '/users/:user_id/recipes/new' => 'recipes#create'

  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'

  post '/recipes/:recipe_id' => 'comments#create'

  resources :users do
    resources :recipes, except: [:destroy]
  end
  resources :recipes do
    resources :comments
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true

  validates :password, :presence => true,
                       :confirmation => true,
                       :length => { minimum: 6 },
                       :unless => :already_has_password?
  has_secure_password

  has_many :recipes
  has_many :ingredients, through: :recipes
  has_many :comments

  def self.find_or_create_from_omniauth(auth_hash)
    user = self.find_by(uid: auth_hash['info']['uid'], provider: auth_hash['provider'])
      if !user.nil?
        return user
      else
        user = User.new
        user.provider = auth_hash.provider
        user.uid = auth_hash.uid
        user.name = auth_hash.name
        user.first_name = auth_hash.first_name
        user.password = SecureRandom.urlsafe_base64
        user.oauth_token = auth_hash.credentials.token
        user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
        user.save!

       if user.save
         return user
       else
         return nil
       end
     end
   end

   def already_has_password?
     !self.password_digest.blank?
   end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = current_user
    @recipes = current_user.recipes

    respond_to do |f|
      f.html { render :show }
      f.json { render json: @recipes }
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: "You have successfully signed in"
    else
      render 'new'
    end
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

  private

  def user_params
    params.require(:user).permit(:name, :password)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= user.name %> has posted <%= user.recipes.count %> recipes<br>
<% end %>

app/views/users/new.html.erb
<h2>New User Sign up!</h2>

<%= form_for @user do |f| %>
  Name:
  <br>
  <%= f.text_field :name %>
<br>
  Password:
  <br>
  <%= f.password_field :password %>
<br>
  <%= f.submit "Submit"%>
<% end %>

app/views/users/show.html.erb
<h1 class ="user"><%= @user.name %>'s Recipes</h1>

<% if current_user.recipes.size == 0 %>
  <h2>Create your first recipe by clicking <%= link_to "Add Recipe", new_user_recipe_path(current_user) %></h2>
<% else %>

<% current_user.recipes.collect do |recipe| %>
  <h3 class="users_recipes">  <%= link_to recipe.name, recipe_path(recipe), id:'user_recipe' %> 
  <p class="recipe_info">  Prep Time: <%= recipe.prep_time_in_minutes %> minutes<br>
  Cook Time: <%= recipe.cook_time_in_minutes %> minutes<br>
  <br>
  </p></h3>
  <button type="button" name="button"> <%= link_to 'Edit', edit_recipe_path(recipe) %> </button>
  <button type="button" name="button"> <%= link_to "Delete", recipe_path(recipe), method: :delete if logged_in? && current_user%> </button>
  <br>
<% end %>
<% end %>