config/routes.rb
Rails.application.routes.draw do

  root to: 'recipes#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  delete '/signout' => 'sessions#destroy'
  get 'auth/google_oauth2/callback' => 'sessions#create'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/users/:user_id/recipes' => 'users#show'
  post '/users/:user_id/recipes/new' => 'recipes#create'

  get 'recipes_sorted_by_cook_time' => 'recipes#sorted_cook_time'

  post '/recipes/:recipe_id' => 'comments#create'

  resources :users do
    resources :recipes, except: [:destroy]
  end
  resources :recipes do
    resources :comments
    post '/comments' => 'comments#create'
  end

  resources :comments, only: [:destroy]
end

app/views/layouts/_errors.html.erb
<% if alert %>
  <div id="notice_wrapper" class="alert">
    <p class="alert"><%= alert %></p>
  </div>
<% elsif notice %>
  <div id="notice_wrapper">
    <p class="notice"><%= notice %></p>
  </div>
<% end %>

app/views/layouts/_form_errors.html.erb
<% if form.errors.any? %>
  <div id="notice_wrapper" class="alert">
    <h3>There were some errors:</h3>
    <ul>
      <% form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<navbar>
  <%if logged_in? %>
    | <%= link_to "Add Recipe", new_user_recipe_path(current_user), id:'create_recipe' %> |
    <%= link_to "#{current_user.name}'s Recipes", user_recipes_path(current_user), id:'users_recipes' %> |
    <%= link_to "Sign out", signout_path, method: :delete %> |
  <% else %>
    <%= link_to "Login", login_path %>
  <%end%>
</navbar>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fun Guy Chef</title>
    <link href="/css/style.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Cormorant+Unicase:700|Acme|Lobster|Philosopher" rel="stylesheet">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <img src="/images/Mushroom_Picture.jpg" class= "center">
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/errors' %>
    <div class="page">
      <h1>Fun Guy Chef</h1>
      <h2>A Fungal Approach to Cooking</h2>
      <h3><%= link_to "All Recipes A-Z", root_path, id:'all_recipes' %> - <%= link_to "Quickest Recipes", recipes_sorted_by_cook_time_path, id:'fastest_recipes' %></h3>
      <div class = "container">
        <%= yield %>
      </div>
  </body>
  </div>
</html>